apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alice
  description: Alice, a member of Team A.
spec:
  profile:
    displayName: Alice
    email: alice@example.com
    picture: https://example.com/alice.jpg

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bob
  description: Bob, a member of Team A.
spec:
  profile:
    displayName: Bob
    email: bob@example.com
    picture: https://example.com/bob.jpg

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: charlie
  description: Charlie, a member of Team B.
spec:
  profile:
    displayName: Charlie
    email: charlie@example.com
    picture: https://example.com/charlie.jpg

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dave
  description: Dave, a member of Team B.
spec:
  profile:
    displayName: Dave
    email: dave@example.com
    picture: https://example.com/dave.jpg
